### PR TITLE
Promise.timeout() indicates time-out more precisely

### PR DESCRIPTION
**Pull request by k7sleeper**
When using Promise.timeout() you may want to differentiate between a promise time-out and other errors. To achive this I have added a TimeOutError class which Promise.timeout() use as rejection reason in case of a time-out.

### CODE REVIEW

**Comment by honzabrecka** [comment]
Please, do not change indentation - add TimeOutError class and change just "new TimeOutError()". Then squash everything into one commit and force push.

**Comment by k7sleeper** [comment]
OK, now?

**Comment by honzabrecka** [comment]
The f8e8748 commit is great! Can you squash everything into just one commit or remove all commits except the last one and force push?

**Comment by k7sleeper** [comment]
How can I do that?

**Comment by honzabrecka** [comment]
`$ git rebase -i HEAD~5` Then delete all lines except the line that contains f8e8748.

https://help.github.com/articles/about-git-rebase

**Comment by k7sleeper** [comment]
done

**Comment by honzabrecka** [comment]
`$ git push -u origin +master`

**Comment by k7sleeper** [comment]
done

**Comment by honzabrecka** [comment]
I don't think so - I'm still seeing 5 commits instead of 1. :)

**Comment by k7sleeper** [comment]
But now, it seems to be ok!

Sorry!

**Comment by honzabrecka** [comment]
Excelent! Thanks!

**Comment by johnyanarella** [comment]
Accepted with minor modifications:
- converted indentation in `TimeOutError.as` from spaces to tabs to match the rest of the project
- renamed `TimeOutError` to `TimeoutError` for naming consistency (i.e. originating method is `timeout()`, not `timeOut()`)
- tweaked comment for `Promise::timeout()` to reference `TimeoutError`
- added comment in `TimeoutError` to reference `Promise::timeout()`

Thank you!

**Pull request merged**
